[build]
  publish = "dist/client"
  command = "npm ci && CI=false node build-for-production.cjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/diagnose"
  to = "/.netlify/functions/diagnose"
  status = 200

[[redirects]]
  from = "/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/fallback"
  to = "/fallback.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5000
  publish = "dist/client"
  autoLaunch = true